// ============================================================================
// Database types — base generated by `supabase gen types typescript`, augmented
// with InnerBloom-specific domain types and row aliases.
// Regenerate the base section when the schema changes; keep augmentations in sync.
// ============================================================================

// ─── JSON primitive (required by supabase-js v2) ────────────────────────────

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

// ─── Generated Database type ─────────────────────────────────────────────────

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      bloom_chat_messages: {
        Row: {
          cards: Json
          content: string
          created_at: string
          id: string
          role: string
          session_id: string
          user_id: string
        }
        Insert: {
          cards?: Json
          content: string
          created_at?: string
          id?: string
          role: string
          session_id: string
          user_id: string
        }
        Update: {
          cards?: Json
          content?: string
          created_at?: string
          id?: string
          role?: string
          session_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "bloom_chat_messages_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "bloom_chat_sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      bloom_chat_sessions: {
        Row: {
          id: string
          last_at: string
          message_count: number
          primary_feeling: string | null
          started_at: string
          title: string | null
          user_id: string
        }
        Insert: {
          id?: string
          last_at?: string
          message_count?: number
          primary_feeling?: string | null
          started_at?: string
          title?: string | null
          user_id: string
        }
        Update: {
          id?: string
          last_at?: string
          message_count?: number
          primary_feeling?: string | null
          started_at?: string
          title?: string | null
          user_id?: string
        }
        Relationships: []
      }
      bloom_posts: {
        Row: {
          anchor_word: string
          category: string
          color_hex: string
          created_at: string
          id: string
          resonance_count: number
          sentence: string
          user_id: string
        }
        Insert: {
          anchor_word: string
          category: string
          color_hex: string
          created_at?: string
          id?: string
          resonance_count?: number
          sentence: string
          user_id: string
        }
        Update: {
          anchor_word?: string
          category?: string
          color_hex?: string
          created_at?: string
          id?: string
          resonance_count?: number
          sentence?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "bloom_posts_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bloom_posts_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      bloom_quotes: {
        Row: {
          author: string | null
          body: string
          categories: string[]
          created_at: string
          id: string
          is_published: boolean
          tone: string
        }
        Insert: {
          author?: string | null
          body: string
          categories: string[]
          created_at?: string
          id?: string
          is_published?: boolean
          tone: string
        }
        Update: {
          author?: string | null
          body?: string
          categories?: string[]
          created_at?: string
          id?: string
          is_published?: boolean
          tone?: string
        }
        Relationships: []
      }
      bloom_reels: {
        Row: {
          audio_key: ReelAudioKey | null
          author_alias: string
          category: string
          color_hex: string
          content: string
          created_at: string
          duration_ms: number
          id: string
          is_published: boolean
        }
        Insert: {
          audio_key?: ReelAudioKey | null
          author_alias: string
          category: string
          color_hex: string
          content: string
          created_at?: string
          duration_ms?: number
          id?: string
          is_published?: boolean
        }
        Update: {
          audio_key?: ReelAudioKey | null
          author_alias?: string
          category?: string
          color_hex?: string
          content?: string
          created_at?: string
          duration_ms?: number
          id?: string
          is_published?: boolean
        }
        Relationships: []
      }
      conversations: {
        Row: {
          closed_at: string | null
          created_at: string
          id: string
          is_kept: boolean
          match_id: string | null
          user_a_id: string
          user_b_id: string
        }
        Insert: {
          closed_at?: string | null
          created_at?: string
          id?: string
          is_kept?: boolean
          match_id?: string | null
          user_a_id: string
          user_b_id: string
        }
        Update: {
          closed_at?: string | null
          created_at?: string
          id?: string
          is_kept?: boolean
          match_id?: string | null
          user_a_id?: string
          user_b_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "conversations_match_id_fkey"
            columns: ["match_id"]
            isOneToOne: true
            referencedRelation: "soul_matches"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conversations_user_a_id_fkey"
            columns: ["user_a_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conversations_user_a_id_fkey"
            columns: ["user_a_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conversations_user_b_id_fkey"
            columns: ["user_b_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conversations_user_b_id_fkey"
            columns: ["user_b_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      daily_intentions: {
        Row: {
          created_at: string
          honored: boolean | null
          id: string
          intention_date: string
          primary_text: string
          tasks: Json
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          honored?: boolean | null
          id?: string
          intention_date?: string
          primary_text?: string
          tasks?: Json
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          honored?: boolean | null
          id?: string
          intention_date?: string
          primary_text?: string
          tasks?: Json
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      hugs: {
        Row: {
          context_id: string
          context_type: string
          created_at: string
          from_user_id: string
          id: string
          to_user_id: string
        }
        Insert: {
          context_id: string
          context_type: string
          created_at?: string
          from_user_id: string
          id?: string
          to_user_id: string
        }
        Update: {
          context_id?: string
          context_type?: string
          created_at?: string
          from_user_id?: string
          id?: string
          to_user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "hugs_from_user_id_fkey"
            columns: ["from_user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "hugs_from_user_id_fkey"
            columns: ["from_user_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "hugs_to_user_id_fkey"
            columns: ["to_user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "hugs_to_user_id_fkey"
            columns: ["to_user_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      institutions: {
        Row: {
          city: string
          created_at: string
          id: string
          name: string
          type: string
        }
        Insert: {
          city: string
          created_at?: string
          id?: string
          name: string
          type: string
        }
        Update: {
          city?: string
          created_at?: string
          id?: string
          name?: string
          type?: string
        }
        Relationships: []
      }
      journal_entries: {
        Row: {
          body: string
          created_at: string
          entry_date: string
          id: string
          updated_at: string
          user_id: string
        }
        Insert: {
          body: string
          created_at?: string
          entry_date?: string
          id?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          body?: string
          created_at?: string
          entry_date?: string
          id?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      kindred_requests: {
        Row: {
          conversation_id: string
          created_at: string
          expires_at: string
          from_user_id: string
          id: string
          note: string | null
          responded_at: string | null
          status: string
          to_user_id: string
        }
        Insert: {
          conversation_id: string
          created_at?: string
          expires_at?: string
          from_user_id: string
          id?: string
          note?: string | null
          responded_at?: string | null
          status?: string
          to_user_id: string
        }
        Update: {
          conversation_id?: string
          created_at?: string
          expires_at?: string
          from_user_id?: string
          id?: string
          note?: string | null
          responded_at?: string | null
          status?: string
          to_user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "kindred_requests_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "conversations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kindred_requests_from_user_id_fkey"
            columns: ["from_user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kindred_requests_from_user_id_fkey"
            columns: ["from_user_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kindred_requests_to_user_id_fkey"
            columns: ["to_user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kindred_requests_to_user_id_fkey"
            columns: ["to_user_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      messages: {
        Row: {
          body: string
          conversation_id: string
          created_at: string
          id: string
          read_at: string | null
          reel_id: string | null
          sender_id: string
        }
        Insert: {
          body: string
          conversation_id: string
          created_at?: string
          id?: string
          read_at?: string | null
          reel_id?: string | null
          sender_id: string
        }
        Update: {
          body?: string
          conversation_id?: string
          created_at?: string
          id?: string
          read_at?: string | null
          reel_id?: string | null
          sender_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "messages_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "conversations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "messages_sender_id_fkey"
            columns: ["sender_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "messages_sender_id_fkey"
            columns: ["sender_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      mood_checkins: {
        Row: {
          anchor_word: string
          category: string
          checkin_date: string
          color_hex: string
          created_at: string
          id: string
          intensity: number
          user_id: string
        }
        Insert: {
          anchor_word: string
          category: string
          checkin_date?: string
          color_hex: string
          created_at?: string
          id?: string
          intensity: number
          user_id: string
        }
        Update: {
          anchor_word?: string
          category?: string
          checkin_date?: string
          color_hex?: string
          created_at?: string
          id?: string
          intensity?: number
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "mood_checkins_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "mood_checkins_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      mood_streaks: {
        Row: {
          current_streak: number
          last_checkin_date: string | null
          longest_streak: number
          updated_at: string
          user_id: string
        }
        Insert: {
          current_streak?: number
          last_checkin_date?: string | null
          longest_streak?: number
          updated_at?: string
          user_id: string
        }
        Update: {
          current_streak?: number
          last_checkin_date?: string | null
          longest_streak?: number
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "mood_streaks_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "mood_streaks_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      onboarding_responses: {
        Row: {
          baseline_mood: string
          blooming_focus: string[]
          checkin_frequency: string
          completed_at: string
          growth_goals: string[]
          notification_opt_in: boolean
          user_id: string
        }
        Insert: {
          baseline_mood: string
          blooming_focus?: string[]
          checkin_frequency: string
          completed_at?: string
          growth_goals?: string[]
          notification_opt_in?: boolean
          user_id: string
        }
        Update: {
          baseline_mood?: string
          blooming_focus?: string[]
          checkin_frequency?: string
          completed_at?: string
          growth_goals?: string[]
          notification_opt_in?: boolean
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "onboarding_responses_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "onboarding_responses_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          anonymous_alias: string
          city: string | null
          created_at: string
          id: string
          institution_id: string | null
          onboarding_completed_at: string | null
          updated_at: string
        }
        Insert: {
          anonymous_alias: string
          city?: string | null
          created_at?: string
          id: string
          institution_id?: string | null
          onboarding_completed_at?: string | null
          updated_at?: string
        }
        Update: {
          anonymous_alias?: string
          city?: string | null
          created_at?: string
          id?: string
          institution_id?: string | null
          onboarding_completed_at?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "profiles_institution_id_fkey"
            columns: ["institution_id"]
            isOneToOne: false
            referencedRelation: "institutions"
            referencedColumns: ["id"]
          },
        ]
      }
      resonances: {
        Row: {
          created_at: string
          post_id: string
          user_id: string
        }
        Insert: {
          created_at?: string
          post_id: string
          user_id: string
        }
        Update: {
          created_at?: string
          post_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "resonances_post_id_fkey"
            columns: ["post_id"]
            isOneToOne: false
            referencedRelation: "bloom_posts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "resonances_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "resonances_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      soul_match_quiz_responses: {
        Row: {
          created_at: string
          current_feeling: string
          energy_level: number
          id: string
          looking_for: string
          openness_level: number
          prompt_answer: string
          quiz_date: string
          user_id: string
        }
        Insert: {
          created_at?: string
          current_feeling: string
          energy_level: number
          id?: string
          looking_for: string
          openness_level: number
          prompt_answer: string
          quiz_date?: string
          user_id: string
        }
        Update: {
          created_at?: string
          current_feeling?: string
          energy_level?: number
          id?: string
          looking_for?: string
          openness_level?: number
          prompt_answer?: string
          quiz_date?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "soul_match_quiz_responses_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "soul_match_quiz_responses_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      soul_matches: {
        Row: {
          created_at: string
          id: string
          match_date: string
          resonance_score: number
          shared_category: string
          status: string
          updated_at: string
          user_a_id: string
          user_b_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          match_date?: string
          resonance_score: number
          shared_category: string
          status?: string
          updated_at?: string
          user_a_id: string
          user_b_id: string
        }
        Update: {
          created_at?: string
          id?: string
          match_date?: string
          resonance_score?: number
          shared_category?: string
          status?: string
          updated_at?: string
          user_a_id?: string
          user_b_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "soul_matches_user_a_id_fkey"
            columns: ["user_a_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "soul_matches_user_a_id_fkey"
            columns: ["user_a_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "soul_matches_user_b_id_fkey"
            columns: ["user_b_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "soul_matches_user_b_id_fkey"
            columns: ["user_b_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      user_push_tokens: {
        Row: {
          created_at: string
          id: string
          platform: string
          token: string
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          platform: string
          token: string
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          platform?: string
          token?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_push_tokens_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_push_tokens_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      public_profiles: {
        Row: {
          anonymous_alias: string | null
          city: string | null
          created_at: string | null
          id: string | null
          institution_id: string | null
        }
        Insert: {
          anonymous_alias?: string | null
          city?: string | null
          created_at?: string | null
          id?: string | null
          institution_id?: string | null
        }
        Update: {
          anonymous_alias?: string | null
          city?: string | null
          created_at?: string | null
          id?: string | null
          institution_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "profiles_institution_id_fkey"
            columns: ["institution_id"]
            isOneToOne: false
            referencedRelation: "institutions"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Functions: {
      close_expired_conversations: { Args: never; Returns: number }
      complete_onboarding: { Args: { payload: Json }; Returns: Json }
      feed_categories_for_mood: {
        Args: { p_category: string }
        Returns: string[]
      }
      intentions_history: {
        Args: { p_days?: number }
        Returns: {
          honored: boolean
          intention_date: string
          primary_text: string
          task_done: number
          task_total: number
        }[]
      }
      kindred_cap: { Args: never; Returns: number }
      kindred_release: { Args: { p_conversation_id: string }; Returns: Json }
      kindred_request_cancel: { Args: { p_request_id: string }; Returns: Json }
      kindred_request_respond: {
        Args: { p_accept: boolean; p_request_id: string }
        Returns: Json
      }
      kindred_request_send: {
        Args: { p_conversation_id: string; p_note?: string }
        Returns: Json
      }
      mood_history: {
        Args: { days?: number }
        Returns: {
          anchor_word: string
          category: string
          color_hex: string
          day: string
          intensity: number
        }[]
      }
      my_kindred_garden: {
        Args: never
        Returns: {
          conversation_id: string
          kept_since: string
          last_message_at: string
          last_message_body: string
          other_alias: string
          other_user_id: string
          shared_category: string
          unread_count: number
        }[]
      }
      my_kindred_status_for_conversation: {
        Args: { p_conversation_id: string }
        Returns: Json
      }
      my_pending_kindred_requests: {
        Args: never
        Returns: {
          conversation_id: string
          created_at: string
          expires_at: string
          from_alias: string
          from_user_id: string
          note: string
          request_id: string
          shared_category: string
        }[]
      }
      reel_category_for_mood: { Args: { p_category: string }; Returns: string }
      send_message: {
        Args: { p_body: string; p_conversation_id: string }
        Returns: Json
      }
      send_push_notification: {
        Args: { p_payload?: Json; p_type: string; p_user_id: string }
        Returns: undefined
      }
      submit_mood_checkin: {
        Args: {
          p_anchor_word: string
          p_category: string
          p_color_hex: string
          p_intensity: number
        }
        Returns: Json
      }
      today_for_me: { Args: never; Returns: Json }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">
type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

// ─── Generated table/view helper types ───────────────────────────────────────

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type InsertTables<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

// ─── InnerBloom domain type aliases ──────────────────────────────────────────

export type IntentionTask = { id: string; label: string; done: boolean };

export type EmotionCategory =
  | 'anxious' | 'sad' | 'stressed' | 'neutral' | 'happy' | 'hopeful';

export type ReelCategory =
  | 'anxiety_stillness'
  | 'depression_hope'
  | 'motivation_direction'
  | 'financial_clarity'
  | 'breaking_patterns'
  | 'rest_recovery';

// Keys map to bundled mp3 loops via src/lib/audio/reel-audio.ts. The DB CHECK
// constraint mirrors this union exactly — keep them in sync.
export type ReelAudioKey =
  | 'ambient'
  | 'rainforest'
  | 'fireplace'
  | 'relaxing_guitar'
  | 'relaxing_water'
  | 'asmr_anxiety';

export type Tone =
  | 'soothing' | 'energizing' | 'grounding' | 'reflective';

export type LookingFor =
  | 'listener' | 'similar_story' | 'perspective' | 'just_presence';

export type CheckinFrequency = 'daily' | 'few_per_week' | 'flexible';
export type MatchStatus      = 'pending' | 'connected' | 'passed';
export type InstitutionType  = 'bpo' | 'university';
export type HugContextType   = 'reel' | 'match' | 'post';

// ─── RPC payload + return types ──────────────────────────────────────────────

export type CompleteOnboardingArgs = {
  payload: {
    baseline_mood: EmotionCategory;
    growth_goals?: string[];
    checkin_frequency: CheckinFrequency;
    blooming_focus?: string[];
    notification_opt_in?: boolean;
    baseline_color_hex?: string;
    baseline_intensity?: number;
    baseline_anchor_word?: string;
  };
};
export type CompleteOnboardingResult = {
  onboarded_at: string;
  baseline_mood: EmotionCategory;
};

export type SubmitMoodCheckinArgs = {
  p_category: EmotionCategory;
  p_intensity: number;
  p_anchor_word: string;
  p_color_hex: string;
};
export type SubmitMoodCheckinResult = {
  mood: MoodCheckinRow;
  streak: MoodStreakRow;
};

export type TodayForMe = {
  mood: MoodCheckinRow | null;
  streak: MoodStreakRow;
  quote: BloomQuoteRow | null;
  reels: BloomReelRow[];
  feed_categories: EmotionCategory[];
};

export type MoodHistoryDay = {
  day: string;
  category: EmotionCategory | null;
  intensity: number | null;
  color_hex: string | null;
  anchor_word: string | null;
};

export type SendMessageArgs = { p_conversation_id: string; p_body: string; p_reel_id?: string | null };
export type SendMessageResult = MessageRow;

// ─── Kindred (Soul Garden) ────────────────────────────────────────────────────

export type KindredRequestStatus =
  | 'pending' | 'accepted' | 'declined' | 'expired' | 'cancelled';

export type KindredRequestRow = {
  id: string;
  conversation_id: string;
  from_user_id: string;
  to_user_id: string;
  note: string | null;
  status: KindredRequestStatus;
  created_at: string;
  responded_at: string | null;
  expires_at: string;
};

export type KindredStatusState = 'none' | 'sent' | 'incoming' | 'kept';

export type KindredStatus =
  | { state: 'none' }
  | { state: 'sent';     request_id: string; sent_at: string }
  | { state: 'incoming'; request_id: string; note: string | null }
  | { state: 'kept' };

export type KindredGardenRow = {
  conversation_id:    string;
  other_user_id:      string;
  other_alias:        string;
  other_display_name: string | null;
  other_avatar_url:   string | null;
  shared_category:    EmotionCategory;
  kept_since:         string;
  last_message_at:    string | null;
  last_message_body:  string | null;
  unread_count:       number;
};

export type PendingKindredRequestRow = {
  request_id:        string;
  conversation_id:   string;
  from_user_id:      string;
  from_alias:        string;
  from_display_name: string | null;
  from_avatar_url:   string | null;
  shared_category:   EmotionCategory;
  note:              string | null;
  created_at:        string;
  expires_at:        string;
};

export type KindredRequestSendArgs = {
  p_conversation_id: string;
  p_note?: string | null;
};
export type KindredRequestRespondArgs = {
  p_request_id: string;
  p_accept: boolean;
};
export type KindredRequestCancelArgs = { p_request_id: string };
export type KindredReleaseArgs       = { p_conversation_id: string };
export type KindredStatusArgs        = { p_conversation_id: string };

// ─── Identity (hybrid: optional display_name + avatar) ───────────────────────

export type SetMyIdentityArgs = {
  p_display_name?: string | null;
  p_avatar_url?: string | null;
};

// ─── Notifications inbox ──────────────────────────────────────────────────────

export type NotificationKind =
  | 'hug' | 'kindred_request' | 'match_found' | 'message';

export type NotificationRow = {
  kind:              NotificationKind;
  event_id:          string;
  from_user_id:      string;
  from_alias:        string;
  from_display_name: string | null;
  from_avatar_url:   string | null;
  context_id:        string;
  preview:           string | null;
  created_at:        string;
  is_unread:         boolean;
};

export type MyNotificationsArgs = { p_limit?: number };

// ─── Convenience row-type aliases ────────────────────────────────────────────

export type ProfileRow             = Tables<'profiles'>;
export type OnboardingResponseRow  = Tables<'onboarding_responses'>;
export type MoodCheckinRow         = Tables<'mood_checkins'>;
export type MoodStreakRow          = Tables<'mood_streaks'>;
export type BloomQuoteRow          = Tables<'bloom_quotes'>;
export type BloomPostRow           = Tables<'bloom_posts'>;
export type ResonanceRow           = Tables<'resonances'>;
export type SoulMatchQuizRow       = Tables<'soul_match_quiz_responses'>;
export type SoulMatchRow           = Tables<'soul_matches'>;
export type ConversationRow        = Tables<'conversations'>;
export type MessageRow             = Tables<'messages'>;
export type BloomReelRow           = Tables<'bloom_reels'>;
export type HugRow                 = Tables<'hugs'>;
export type JournalEntryRow        = Tables<'journal_entries'>;
export type DailyIntentionRow      = Tables<'daily_intentions'>;
